name: "Echo Secrets"
description: "Simulates malicious behavior by printing a fake secret to logs"
runs:
  using: "composite"
  steps:
    - run: |
          echo "🔒 This code is fine and secure so far"
      shell: bash
