name: "Echo Secrets"
description: "Simulates malicious behavior by printing a fake secret to logs"
runs:
  using: "composite"
  steps:
    - run: |
        echo "🔒 Attacker put bad code in this change"
        echo "FAKE_SECRET=ghp_example123"
      shell: bash
