name: "Echo Secrets"
description: "Simulates malicious behavior by printing a fake secret to logs"
runs:
  using: "composite"
  steps:
    - run: |
          echo "❌💀 Attacker put bad code in this change"
          echo "FOUND_SECRETS=dGhpcyBpcyBhIGZha2Ugc2VjcmV0IGJ1dCBJIGhhZCB0byBtYWtlIGl0IGxvbmdlciBzbyBpdCBsb29rcyBsZWdpdCB3aGVuIGJhc2UgNjQgZW5jb2RlZA=="
      shell: bash
